USE DB_NEWSAPP

CREATE PROCEDURE LOGS_ADD @ID VARCHAR(200), @APIName NVARCHAR(MAX), @MethodName NVARCHAR(MAX), @Description NVARCHAR(MAX), @Params NVARCHAR(MAX), @CreatedDate DATETIME2
AS
	BEGIN
		INSERT INTO dbo.LOGS(ID, APIName, MethodName, Description, Params, CreatedDate) VALUES (@ID, @APIName, @MethodName, @Description, @Params, @CreatedDate);
	END


CREATE PROCEDURE LOGS_GETALL
AS
	BEGIN
		SELECT * FROM LOGS ORDER BY CreatedDate DESC;
	END


CREATE PROCEDURE MENUTYPES_GETALL
AS
	BEGIN
		SELECT * FROM MENUTYPES;
	END


